MODEL:
  NAME: "deeplab_vgg16"
  # weights from https://github.com/jcjohnson/pytorch-vgg
  # please note that a different classifier name is defined as stated in https://github.com/jcjohnson/pytorch-vgg/issues/3
  WEIGHTS: "https://web.eecs.umich.edu/~justincj/models/vgg16-00b39a1b.pth"
DATASETS:
  SOURCE_TRAIN: "cityscapes_self_distill_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1024, 512)
  INPUT_SIZE_TEST: (2048, 1024)
  INPUT_SCALES_TRAIN: (0.5, 1.5)
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  PIXEL_MEAN: [103.939, 116.779, 123.68]
  PIXEL_STD: [1., 1., 1.]
  TO_BGR255: True
SOLVER:
  BASE_LR: 5e-4
  MAX_ITER: 31250
  STOP_ITER: 20000
  BATCH_SIZE: 8
